version: '3.8'

services:
  api:
    build:
      context: .
      target: runner-api
    image: code0ex/ecowatch-api:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    networks:
      - ecowatch-network
    depends_on:
      - db

  web:
    build:
      context: .
      target: runner-web
    image: code0ex/ecowatch-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://api:3001/api
    depends_on:
      - api
    networks:
      - ecowatch-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecowatch
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecowatch-network

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecowatch-network

  influxdb:
    image: influxdb:2.7-alpine
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - ecowatch-network

networks:
  ecowatch-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  influxdb_data: 